/**
 * Bairros e distritos das cidades atendidas (OpenStreetMap via Overpass, 07/10/2026,
 * mais alguns conhecidos que o mapa não trouxe). Sem os nomes genéricos ("Centro")
 * ou que são bairro famoso de outra cidade ("Morumbi", "Santa Cecília").
 * Uma cidade nova entra aqui quando um cliente dela começar a usar.
 */
export const BAIRROS: Record<string, string[]> = {
 "Campinas/SP": [
  "Bacuri",
  "Barão Geraldo",
  "Bela Aliança Bairro & Parque",
  "Cambuí",
  "Caminhos de San Conrado",
  "Chacara Santa Margarida",
  "Chácara Belvedere",
  "Chácara Primavera",
  "Chácara São Francisco",
  "Chácara da Barra",
  "Chácaras São Martinho",
  "Cidade Satélite Iris",
  "Cidade Universitária",
  "Comunidade Parque Brasilia",
  "Condominio Pirapora do Bom Jesus",
  "Condomínio Chácaras Grota Azul",
  "Conjunto Habitacional Parque Itajai",
  "Jardim Alto da Cidade Universitária",
  "Jardim Andorinhas",
  "Jardim Antonio Von Zuben",
  "Jardim Aurélia",
  "Jardim Bassoli",
  "Jardim Campo Belo",
  "Jardim Carlos Lourenço",
  "Jardim Chapadão",
  "Jardim Garcia",
  "Jardim Guanabara",
  "Jardim Madalena",
  "Jardim Marisa",
  "Jardim Mirassol",
  "Jardim Miriam",
  "Jardim Nova Europa",
  "Jardim Nova Mercedes",
  "Jardim Novo Campos Elíseos",
  "Jardim Paulicéia",
  "Jardim Proença",
  "Jardim Professora Tarcília",
  "Jardim San Diego",
  "Jardim Santa Genebra",
  "Jardim Santa Genebra 2",
  "Jardim Santa Monica",
  "Jardim Sao Bento",
  "Jardim São Marcos",
  "Jardim Yeda",
  "Jardim das Bandeiras",
  "Jardim das Paineiras",
  "Joaquim Egídio",
  "Loteamento Parque Centenário",
  "Loteamento Vila Esperanca",
  "Loteamento Vila San Martin",
  "Mansões Santo Antônio",
  "Nova Aparecida",
  "Nova Boa Vista",
  "Nova Campinas",
  "Núcleo Habitacional Lech Walesa",
  "Núcleo Residencial Jardim Campo Grande - Cidade Satélite Íris",
  "Núcleo Residencial Jardim Campos Elísios",
  "Núcleo Residencial Jardim Capivari",
  "Núcleo Residencial Jardim Florence",
  "Núcleo Residencial Jardim Novos Campos Elísios",
  "Núcleo Residencial Jardim Yeda",
  "Núcleo Residencial Princesa do Oeste",
  "Ouro Verde",
  "Parque Dos Pomares",
  "Parque Fazenda Santa Cândida",
  "Parque Industrial",
  "Parque Itália",
  "Parque Jambeiro",
  "Parque Taquaral",
  "Parque Universitário de Viracopos",
  "Parque das Universidades",
  "Parque do M. Dom Pedro II",
  "Pedra Branca",
  "Polo de Alta Tecnologia de Campinas - Polo I",
  "Recanto Dos Dourados",
  "Reforma Agraria",
  "Residencial Barão do Café",
  "Residencial Kairos",
  "Residencial Takanos",
  "Residencial Vila Olimpia",
  "San Martin",
  "Sousas",
  "Sítios de Recreio Gramado",
  "Taquaral",
  "Terras de Friburgo",
  "Três Vendas",
  "Vila Abaeté",
  "Vila Aeroporto",
  "Vila Brandina",
  "Vila Costa e Silva",
  "Vila Industrial",
  "Vila Itapura",
  "Vila Lutécia",
  "Vila Miguel Vicente Cury",
  "Vila Padre Anchieta",
  "Vila Palácios",
  "Vila San Martin",
  "Vila Santa Isabel",
  "Vila Virginia"
 ],
 "Paulínia/SP": [
  "Alvorada Parque",
  "Balneário Tropical",
  "Belvedere do Lago",
  "Betel",
  "Capim Fino - Saltinho",
  "Distrito Industrial de Betel",
  "Dona Edith de Campos Fávero",
  "Fazenda Bela Vista",
  "Jardim Amélia Duarte Quintal",
  "Jardim Cabreúva",
  "Jardim Flamboyant",
  "Jardim Harmonia",
  "Jardim Monte Alegre I",
  "Jardim Monte Alegre II",
  "Jardim Vista Alegre",
  "Jardim de Itapoan",
  "Jardim dos Calegaris",
  "João Aranha",
  "Metropolitan Park",
  "Nova Paulínia",
  "Nova Veneza",
  "Parque Bom Retiro",
  "Parque Brasil 500",
  "Parque da Figueira",
  "Parque da Represa",
  "Parque das Indústrias",
  "Recanto dos Pássaros",
  "Represa do Salto Grande",
  "Reserva São Fernando",
  "Saltinho",
  "Vila Bressani",
  "Vila José Paulino Nogueira",
  "Vila Karsher",
  "Vila Monte Alegre",
  "Vila Nunes",
  "Vila Presidente Médici"
 ]
};
